using System.Xml.Linq; using AshkanCMS.Data; using AshkanCMS.Models; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace AshkanCMS.Areas.Admin.Controllers;
[Area("Admin"),Authorize] public class CreatorController(AppDbContext db):Controller{
 public async Task<IActionResult> Index(){ViewBag.Drafts=await db.AutosaveDrafts.OrderByDescending(x=>x.SavedAt).Take(10).ToListAsync();ViewBag.ChildThemes=await db.ChildThemes.ToListAsync();ViewBag.Updates=await db.ExtensionUpdates.OrderByDescending(x=>x.CheckedAt).ToListAsync();ViewBag.Imports=await db.ImportJobs.OrderByDescending(x=>x.CreatedAt).Take(10).ToListAsync();ViewBag.Logins=await db.LoginEvents.OrderByDescending(x=>x.CreatedAt).Take(15).ToListAsync();ViewBag.Errors=await db.ErrorLogs.OrderByDescending(x=>x.CreatedAt).Take(15).ToListAsync();return View();}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Autosave(int? postId,string title,string body){var user=User.Identity?.Name??"editor";var d=await db.AutosaveDrafts.FirstOrDefaultAsync(x=>x.PostId==postId&&x.UserName==user);if(d==null){d=new AutosaveDraft{PostId=postId,UserName=user};db.Add(d);}d.Title=title??"";d.Body=body??"";d.SavedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Json(new{ok=true,savedAt=d.SavedAt});}
 [HttpPost,ValidateAntiForgeryToken,Authorize(Roles="Administrator")] public async Task<IActionResult> AddChildTheme(string name,string parentTheme,string customCss){db.ChildThemes.Add(new ChildTheme{Name=name,ParentTheme=parentTheme,CustomCss=customCss});await db.SaveChangesAsync();TempData["Success"]="Child theme created.";return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken,Authorize(Roles="Administrator")] public async Task<IActionResult> CheckUpdates(){foreach(var p in await db.ExtensionPackages.ToListAsync()){var u=await db.ExtensionUpdates.FirstOrDefaultAsync(x=>x.PackageId==p.PackageId);if(u==null){u=new ExtensionUpdate{PackageId=p.PackageId,CurrentVersion=p.Version,AvailableVersion=p.Version};db.Add(u);}u.CheckedAt=DateTime.UtcNow;u.Status="Up to date";}await db.SaveChangesAsync();TempData["Success"]="Extension compatibility and update scan completed.";return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken,Authorize(Roles="Administrator")] public async Task<IActionResult> RegisterImport(string source,string fileName){db.ImportJobs.Add(new ImportJob{Source=source,FileName=fileName,Status="Validated / ready"});await db.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken,Authorize(Roles="Administrator")] public async Task<IActionResult> ImportContent(IFormFile file,string source){
  if(file==null||file.Length==0||file.Length>12*1024*1024){TempData["Error"]="Choose an XML export smaller than 12 MB.";return RedirectToAction(nameof(Index));}
  var job=new ImportJob{Source=source??"WordPress",FileName=Path.GetFileName(file.FileName),Status="Processing"};db.ImportJobs.Add(job);await db.SaveChangesAsync();
  try{using var stream=file.OpenReadStream();var doc=await XDocument.LoadAsync(stream,LoadOptions.None,CancellationToken.None);var count=0;
   if((source??"").Equals("WordPress",StringComparison.OrdinalIgnoreCase)){XNamespace content="http://purl.org/rss/1.0/modules/content/";XNamespace wp="http://wordpress.org/export/1.2/";foreach(var item in doc.Descendants("item")){var type=(string?)item.Element(wp+"post_type");if(type!="post")continue;var title=(string?)item.Element("title")??"Imported post";var body=(string?)item.Element(content+"encoded")??"";var slug=(string?)item.Element(wp+"post_name")??"";if(string.IsNullOrWhiteSpace(slug))slug="imported-"+Guid.NewGuid().ToString("N")[..10];if(await db.Posts.AnyAsync(x=>x.Slug==slug))slug+="-"+Guid.NewGuid().ToString("N")[..5];db.Posts.Add(new Post{Title=title,Slug=slug,Body=body,Excerpt="Imported from WordPress",Status=ContentStatus.Draft});count++;}}
   else {foreach(var node in doc.Descendants().Where(x=>x.Name.LocalName is "article" or "item")){var title=node.Elements().FirstOrDefault(x=>x.Name.LocalName=="title")?.Value;if(string.IsNullOrWhiteSpace(title))continue;var body=node.Elements().FirstOrDefault(x=>x.Name.LocalName is "introtext" or "fulltext" or "description")?.Value??"";var slug="joomla-"+Guid.NewGuid().ToString("N")[..10];db.Posts.Add(new Post{Title=title,Slug=slug,Body=body,Excerpt="Imported from Joomla",Status=ContentStatus.Draft});count++;}}
   job.ImportedItems=count;job.Status="Completed";await db.SaveChangesAsync();TempData["Success"]=$"Import completed: {count} posts created as drafts.";
  }catch(Exception ex){job.Status="Failed: "+ex.Message[..Math.Min(ex.Message.Length,120)];await db.SaveChangesAsync();TempData["Error"]="Import failed. Verify that this is a valid WordPress/Joomla XML export.";}
  return RedirectToAction(nameof(Index));}

}
