using AshkanCMS.Data; using AshkanCMS.Models; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace AshkanCMS.Areas.Admin.Controllers;
[Area("Admin"),Authorize] public class EnterpriseController(AppDbContext db):Controller{
 public async Task<IActionResult> CommandCenter(){ViewBag.Posts=await db.Posts.CountAsync();ViewBag.Drafts=await db.Posts.CountAsync(x=>x.Status==ContentStatus.Draft);ViewBag.Users=await db.Users.CountAsync();ViewBag.Forms=await db.Forms.CountAsync();ViewBag.Media=await db.Media.CountAsync();ViewBag.AiRuns=await db.AiHistory.CountAsync();ViewBag.Recent=await db.AuditEntries.OrderByDescending(x=>x.CreatedAt).Take(8).ToListAsync();return View();}
 public async Task<IActionResult> GlobalSearch(string q=""){ViewBag.Q=q;ViewBag.Posts=string.IsNullOrWhiteSpace(q)?[]:await db.Posts.Where(x=>x.Title.Contains(q)||x.Body.Contains(q)).Take(20).ToListAsync();ViewBag.Pages=string.IsNullOrWhiteSpace(q)?[]:await db.Pages.Where(x=>x.Title.Contains(q)||x.Body.Contains(q)).Take(20).ToListAsync();return View();}
 [Authorize(Roles="Administrator")] public async Task<IActionResult> Security(){ViewBag.Users=await db.Users.CountAsync();ViewBag.Admins=await db.Users.CountAsync(x=>x.Role=="Administrator");ViewBag.Events=await db.SecurityEvents.OrderByDescending(x=>x.CreatedAt).Take(50).ToListAsync();return View();}
 [Authorize(Roles="Administrator")] public async Task<IActionResult> Webhooks()=>View(await db.Webhooks.OrderBy(x=>x.Name).ToListAsync());
 [HttpPost,ValidateAntiForgeryToken,Authorize(Roles="Administrator")] public async Task<IActionResult> AddWebhook(string name,string url,string eventName){if(Uri.TryCreate(url,UriKind.Absolute,out _)){db.Webhooks.Add(new WebhookDefinition{Name=name,Url=url,EventName=eventName});await db.SaveChangesAsync();TempData["Success"]="Webhook added.";}else TempData["Error"]="Enter a valid absolute URL.";return RedirectToAction(nameof(Webhooks));}
}
