using System.ComponentModel.DataAnnotations;
namespace AshkanCMS.Models;
public class ThemeDefinition { public int Id {get;set;} [Required] public string Name {get;set;}="Aurora"; public string Description {get;set;}=""; public string PreviewClass {get;set;}="theme-aurora"; public bool IsActive {get;set;} }
public class PluginDefinition { public int Id {get;set;} [Required] public string Name {get;set;}=""; public string Description {get;set;}=""; public string Version {get;set;}="1.0.0"; public bool IsEnabled {get;set;} }
public class AuditEntry { public int Id {get;set;} public string UserName {get;set;}="system"; public string Action {get;set;}=""; public string Entity {get;set;}=""; public string Details {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class SeoSetting { public int Id {get;set;} public string DefaultTitle {get;set;}="Ashkan CMS"; public string DefaultDescription {get;set;}="Modern ASP.NET Core CMS"; public string Robots {get;set;}="index,follow"; public string SocialImage {get;set;}=""; public bool GenerateSitemap {get;set;}=true; }
public class UserCreateVm { [Required,MaxLength(80)] public string UserName {get;set;}=""; [Required,MinLength(8),DataType(DataType.Password)] public string Password {get;set;}=""; [Required] public string Role {get;set;}="Editor"; public string DisplayName {get;set;}=""; }
public class TagDefinition { public int Id {get;set;} [Required,MaxLength(80)] public string Name {get;set;}=""; public string Slug {get;set;}=""; }
public class ContentRevision { public int Id {get;set;} public int PostId {get;set;} public string Title {get;set;}=""; public string Body {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public string CreatedBy {get;set;}="system"; }
public class WidgetDefinition { public int Id {get;set;} [Required] public string Title {get;set;}=""; public string Type {get;set;}="Text"; public string Content {get;set;}=""; public string Zone {get;set;}="Sidebar"; public int SortOrder {get;set;} public bool IsEnabled {get;set;}=true; }
public class NotificationItem { public int Id {get;set;} public string Title {get;set;}=""; public string Message {get;set;}=""; public bool IsRead {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class FormDefinition { public int Id {get;set;} [Required,MaxLength(120)] public string Name {get;set;}="Contact form"; public string Slug {get;set;}="contact"; public string FieldsJson {get;set;}="name,email,message"; public bool IsActive {get;set;}=true; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class FormSubmission { public int Id {get;set;} public int FormDefinitionId {get;set;} public string Payload {get;set;}=""; public string IpAddress {get;set;}=""; public bool IsRead {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class RedirectRule { public int Id {get;set;} [Required] public string FromPath {get;set;}=""; [Required] public string ToPath {get;set;}="/"; public int StatusCode {get;set;}=301; public bool IsEnabled {get;set;}=true; }
public class LanguageDefinition { public int Id {get;set;} [Required] public string Code {get;set;}="en"; public string Name {get;set;}="English"; public bool IsRtl {get;set;} public bool IsDefault {get;set;} }
public class ScheduledJob { public int Id {get;set;} public string Name {get;set;}="Publish content"; public string JobType {get;set;}="Publish"; public DateTime RunAt {get;set;}=DateTime.UtcNow.AddHours(1); public string Status {get;set;}="Queued"; public string Payload {get;set;}=""; }
public class CustomizerSetting { public int Id {get;set;} public string BrandName {get;set;}="Ashkan CMS"; public string PrimaryColor {get;set;}="#6750A4"; public string SurfaceStyle {get;set;}="Soft"; public string FontScale {get;set;}="Comfortable"; public bool CompactSidebar {get;set;} }
public class AiSetting { public int Id {get;set;} public bool IsEnabled {get;set;}=true; public string Provider {get;set;}="Local Smart Assistant"; public string Model {get;set;}="Ashkan Editorial Copilot"; public string Endpoint {get;set;}=""; public string ApiKey {get;set;}=""; public double Temperature {get;set;}=.4; public string DefaultLanguage {get;set;}="English"; }
public class AiHistoryItem { public int Id {get;set;} public string Tool {get;set;}="Assistant"; public string Prompt {get;set;}=""; public string Result {get;set;}=""; public string UserName {get;set;}="system"; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class SecurityEvent { public int Id {get;set;} public string EventType {get;set;}="Info"; public string UserName {get;set;}="system"; public string Details {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class WebhookDefinition { public int Id {get;set;} public string Name {get;set;}="Webhook"; public string Url {get;set;}=""; public string EventName {get;set;}="content.published"; public bool IsEnabled {get;set;}=true; }
public class ExtensionPackage { public int Id {get;set;} [Required] public string PackageId {get;set;}=""; [Required] public string Name {get;set;}=""; public string Type {get;set;}="Plugin"; public string Version {get;set;}="1.0.0"; public string Author {get;set;}=""; public string Description {get;set;}=""; public string InstallPath {get;set;}=""; public bool IsEnabled {get;set;}=true; public DateTime InstalledAt {get;set;}=DateTime.UtcNow; }
public class WorkflowItem { public int Id {get;set;} public string Title {get;set;}=""; public string ContentType {get;set;}="Post"; public string Status {get;set;}="Pending review"; public string AssignedTo {get;set;}="Administrator"; public DateTime UpdatedAt {get;set;}=DateTime.UtcNow; }
public class CrmContact { public int Id {get;set;} [Required] public string Name {get;set;}=""; public string Email {get;set;}=""; public string Company {get;set;}=""; public string Stage {get;set;}="Lead"; public string Notes {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class NewsletterSubscriber { public int Id {get;set;} [Required] public string Email {get;set;}=""; public string Name {get;set;}=""; public bool IsActive {get;set;}=true; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class ApiToken { public int Id {get;set;} public string Name {get;set;}="Integration"; public string TokenHash {get;set;}=""; public string Prefix {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime? LastUsedAt {get;set;} public bool IsRevoked {get;set;} }
public class SystemPreference { public int Id {get;set;} public bool MaintenanceMode {get;set;} public bool CookieConsent {get;set;}=true; public bool EnablePublicApi {get;set;}=true; public int CacheMinutes {get;set;}=15; public string ContactEmail {get;set;}="admin@example.com"; }
public class TrashItem { public int Id {get;set;} public string EntityType {get;set;}="Post"; public int EntityId {get;set;} public string Title {get;set;}=""; public string PayloadJson {get;set;}=""; public string DeletedBy {get;set;}="system"; public DateTime DeletedAt {get;set;}=DateTime.UtcNow; }
public class PermissionGrant { public int Id {get;set;} public string Role {get;set;}="Editor"; public string Permission {get;set;}="content.edit"; public bool Allowed {get;set;}=true; }
public class LoginEvent { public int Id {get;set;} public string UserName {get;set;}=""; public bool Success {get;set;} public string IpAddress {get;set;}=""; public string UserAgent {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class ErrorLogEntry { public int Id {get;set;} public string Path {get;set;}=""; public string ErrorType {get;set;}=""; public string Message {get;set;}=""; public string TraceId {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class ExtensionHook { public int Id {get;set;} public string HookName {get;set;}="content.afterSave"; public string PackageId {get;set;}=""; public int Priority {get;set;}=10; public bool IsEnabled {get;set;}=true; }
public class AutosaveDraft { public int Id {get;set;} public int? PostId {get;set;} public string UserName {get;set;}=""; public string Title {get;set;}=""; public string Body {get;set;}=""; public DateTime SavedAt {get;set;}=DateTime.UtcNow; }
public class ChildTheme { public int Id {get;set;} public string Name {get;set;}="Ashkan Child"; public string ParentTheme {get;set;}="Aurora"; public string CustomCss {get;set;}=""; public bool IsActive {get;set;} }
public class ExtensionUpdate { public int Id {get;set;} public string PackageId {get;set;}=""; public string CurrentVersion {get;set;}="1.0.0"; public string AvailableVersion {get;set;}="1.0.0"; public string Status {get;set;}="Up to date"; public DateTime CheckedAt {get;set;}=DateTime.UtcNow; }
public class ImportJob { public int Id {get;set;} public string Source {get;set;}="WordPress"; public string FileName {get;set;}=""; public string Status {get;set;}="Ready"; public int ImportedItems {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class BackgroundTaskItem { public int Id {get;set;} public string Name {get;set;}=""; public string TaskType {get;set;}="Maintenance"; public string Status {get;set;}="Queued"; public int Progress {get;set;} public string Details {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime? CompletedAt {get;set;} }
public class BackupSnapshot { public int Id {get;set;} public string Name {get;set;}=""; public string FileName {get;set;}=""; public long SizeBytes {get;set;} public string Status {get;set;}="Ready"; public string CreatedBy {get;set;}="system"; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class MediaOptimizationRecord { public int Id {get;set;} public int? MediaItemId {get;set;} public string FileName {get;set;}=""; public long OriginalBytes {get;set;} public long OptimizedBytes {get;set;} public string Format {get;set;}="Original"; public string Status {get;set;}="Analyzed"; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class WebhookDelivery { public int Id {get;set;} public int? WebhookDefinitionId {get;set;} public string EventName {get;set;}=""; public string TargetUrl {get;set;}=""; public int StatusCode {get;set;} public string Status {get;set;}="Pending"; public int Attempt {get;set;}=1; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
